version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: restaurant_db
    environment:
      POSTGRES_USER: tkd_desarrollo
      POSTGRES_PASSWORD: Dkubi2025+
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./server
    container_name: restaurant_server
    environment:
      DATABASE_URL: "postgresql://tkd_desarrollo:Dkubi2025+@postgres:5432/restaurant"
      JWT_SECRET: "tu_jwt_secret_super_secreto"
      JWT_EXPIRE: "7d"
      PORT: 3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX: 100
    ports:
      - "3001:3000"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: restaurant_client
    environment:
      VITE_URL_SERVER: http://server:3000
    ports:
      - "4174:4173"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
