name: Build, Push, and Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPO_OWNER_LOWER: ${{ github.repository_owner }}
  SERVER_IMAGE_NAME: "restaurant-server"
  CLIENT_IMAGE_NAME: "restaurant-client"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.SERVER_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.SERVER_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.CLIENT_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.CLIENT_IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build-and-push-image

    permissions:
      contents: read
      packages: read # Permiso para leer imágenes en GHCR
      id-token: write # Permiso para autenticarse con GHCR

    steps:
      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image from GitHub
        run: |
          docker pull ghcr.io/${{ env.REPO_OWNER_LOWER }}/${{ env.IMAGE_NAME }}:latest || exit 1

      - name: Stop and remove existing container
        run: |
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

      - name: Run Docker container
        run: |
          docker run -d --name ${{ env.CONTAINER_NAME }} -p 3000:3000 
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.IMAGE_NAME }}:latest
